### ISSUE TITLE
problem with python multiprocessing?

### ISSUE THREAD

**Issue by halfluke** [securing/DumpsterDiver#43]
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 692, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 674, in _help_stuff_finish
    inqueue._reader.recv()
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 933, in RebuildProxy
    return func(token, serializer, incref=incref, **kwds)
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 981, in AutoProxy
    proxy = ProxyType(token, serializer, manager=manager, authkey=authkey,
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 783, in __init__
    self._incref()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 837, in _incref
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

Connection refused to what? It's a local file I am running dumpsterdiver against...
I found the reference to multiprocessing in core.py and I removed it and now it works.
What's wrong with python multiprocessing module??

**Comment by halfluke** [comment]
apparently solved by putting time.sleep(1) after the "while" in core.py
def mp_handler(queue, result, settings):
    # depending on your hardware the DumpsterDiver will use all available cores for
    # parallel processing

    p = multiprocessing.Pool(multiprocessing.cpu_count())
    while queue.qsize():
        time.sleep(1)
        p.apply_async(worker, (queue,result,settings))
    queue.join()
Still curious to know if it should be considered a multiprocessing module issue...
